### 라이브러리 불러오기


In [2]:
import numpy as np
# numpy 라이브러리를 가져와서 np라고 부르겠다. 
# numpy라이브러리를 데리고왔고 개는 배열을 제공하니 배열을만들어보자

### 1차원 배열(array) 만들기

In [3]:
list1 = [1,2,3,4,5]
list1
# 리스트라는 변수를 만들었고 이걸 이용해서 어레이라는 객체를 만들어보겠음

[1, 2, 3, 4, 5]

In [4]:
np.array(list1)  # numpy에 있는 array라는 자료형
#배열을 만들어주는함수

array([1, 2, 3, 4, 5])

### 2차원 배열(array) 만들기

In [5]:
list2 = [[1,2,3],[4,5,6]] # 2차원 리스트 만들기 -> 대괄호가 2개씩 나오면됨
list2

[[1, 2, 3], [4, 5, 6]]

In [8]:
arr2 = np.array(list2)
# np에 있는 어레이 만들기
#이렇게 만든 배열을  arr2라는 변수에 담아줌

In [9]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

### 배열 확인
- shape : 배열의 크기  (행, 열)
- size : 총 요소 개수 확인
- ndim : 배열의 차원 확인
##### 이세가지 함수를 같이 이용해보자(매개변수가 필요없는함수라고생각하기-- 뒤에 괄호가 안붙음)

In [14]:
arr2.shape


(2, 3)

In [15]:
arr2.size

6

In [16]:
arr2.ndim

2

In [17]:
# 배열의 타입 확인 - 데이터타입
arr2.dtype

dtype('int32')

- 3차원 배열 만들고 확인하기

In [28]:
# 3차원 list 만들기
list3 = [[[1,2],[3,4]],[[5,6],[7,8]]]
list3

[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]

In [27]:
# 3차원 array 만들기 ( 파이썬엔 없음 np라는 라이브러리에만 배열만들어주는 기능있음)
arr3 = np.array(list3)
arr3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [26]:
print(f"배열의 크기 : {arr3.shape}")
print(f"배열의 차원 : {arr3.ndim}")
print(f"배열의 개수 : {arr3.size}")

배열의 크기 : (2, 2, 2)
배열의 차원 : 3
배열의 개수 : 8


### array 더 만들어보자

#### 특정 값으로 배열 생성

In [29]:
# 0으로 이루어진 배열 생성
# zeros((행,열)) ㅇ행 ㅇ열의 0으로만 이루어진 배열을 생성해라
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
# 1로만 이루어진 배열 생성
# ones((행,열)) 
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [31]:
# 원하는 값으로 이루어진 배열 생성
np.full((3,3),3)
# full((행,열),채울 숫자)


array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

- 범위 배열 생성하기

In [34]:
# 1~50
list1 = []    #일단 빈 리스트 만들어주기
for i in range(1,51):
    list1.append(i)    #추가해주는 함수 append()
list1

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50]

In [35]:
#먼저 리스트 만들고 배열!
np.array(list1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [37]:
# 범위 배열 만드는 함수  (for문사용안하고 한꺼번에 만들 수 있음)
np.arange(1,51)
#range처럼 증가값도 추가해줄 수 잇음

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

- 난수(랜덤한값) 배열 생성하기 

In [38]:
# 랜덤 값 생성하기
# 0~1 사이 값 생성
np.random.rand(2,3)

array([[0.65764053, 0.14953307, 0.06955677],
       [0.66604678, 0.34362072, 0.4335031 ]])

In [39]:
# 랜덤 정수 생성하기
#(시작값, n-1) 사이의 랜덤한 정수 1개 생성
np.random.randint(2,10)

6

In [42]:
np.random.randint(2,10, size=(2,3))

array([[7, 2, 5],
       [4, 7, 2]])

# array 연산

In [43]:
list1 = [1,2,3,4]
list2 = [5,6,7,8]
list2

[5, 6, 7, 8]

In [45]:
list1 + list2

[1, 2, 3, 4, 5, 6, 7, 8]

In [46]:
#같은 자리끼리 연산시키려면!
# array연산
arr1 = np.array(list1)
arr2 = np.array(list2)

In [48]:
arr1 + arr2

array([ 6,  8, 10, 12])

- array에는 index를 이용한 순서활용가능 -> 인덱싱, 슬라이싱 가능!

### 인덱싱, 슬라이싱

그 위치에 있는 값을 불러오거나 잘라오는

In [58]:
# 슬라이싱
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
arr1[3:7]

array([3, 4, 5, 6])

In [50]:
# 0~49 배열
np.arange(50)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [53]:
#2차원 배열로 만들기
# 1차원 배열의 크기를 재지정 = reshape(크기)
arr2 = np.arange(50).reshape(5,10)


In [54]:
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [ ]:
#2차원 배열 슬라이싱
# 슬라이싱 할 볌위 지정 해줘야함.      차원 = 방향 차원이 늘어난다는건 방향이 늘어난다는것 (점이 늘어나서 선이생겨 방향이 생기는거처럼)
# 2차원은 차원이 늘어난거닌까 행 열 방향 둘다 지정해줘야함
#[ 행의범위 , 열의 범위]

In [60]:
# 슬라이싱
# [ : n] - 처음부터 n-1까지
# [ n : ] - n부터 끝까지
#[ : ] - 처음부터 끝까지
arr2[ 0:2 , :]
arr2[ :2 ]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [65]:
arr2[ : , 0]

array([ 0, 10, 20, 30, 40])

In [70]:
print(arr2[2:3,3:4])
print(arr2[2,3])

[[23]]
23


In [71]:
print(arr2[2:3,1:2])
print(arr2[2,1])

[[21]]
21


In [73]:
# 숫자 23, 21 한꺼번에 불러오기

arr2[ [2,2],[3,1]]
#       행    열

array([23, 21])

# BMI 실습
#### BMI구하기

In [79]:
# 데이터 불러오기
#np.loadtxt('파일명.확장자',)
# 구분기호 delimiter  --- 안에서 데이터를 구분하는 기호가 뭐인지 알려줘야함.
data = np.loadtxt( 'height_weight.txt', delimiter =',')
print(data)

[[175.2 180.3 175.  169.2 185.2 188.  177.6 178.2 177.  179. ]
 [ 65.6  88.   79.2  69.3  55.   71.2  73.   68.9  74.   82. ]]


In [87]:
# 1. 키, 몸무게를 나누어 담기(인덱싱/슬라이싱)

weight = np.array(data[1: , ])
# weight = np.array(data[0])

height = np.array(data[ :1, ])
# height = np.array(data[1])

In [88]:
print(weight)
print(height)

[[65.6 88.  79.2 69.3 55.  71.2 73.  68.9 74.  82. ]]
[[175.2 180.3 175.  169.2 185.2 188.  177.6 178.2 177.  179. ]]


In [ ]:
# 2.키 단위 맞추기 ( cm -> m,  *0.01 or /100)

In [94]:
height_m = height * 0.01
print(height_m)

[[1.752 1.803 1.75  1.692 1.852 1.88  1.776 1.782 1.77  1.79 ]]


In [95]:
# 3. bmi 계산하기
# 몸무게 / (키(m)) *(키(m))

bmi = weight / (height_m*height_m)
print(bmi)

[[21.37153104 27.07018468 25.86122449 24.20652885 16.03543423 20.14486193
  23.14392095 21.69720651 23.62028791 25.59220998]]


# Boolean 인덱싱
#### (원래는 인덱스 번호 0,1,2,3 같은걸로 인덱싱하는데 불리언 값으로 인덱싱하는방법)
#### 조건필터링이 가능 - 조건에따라서 값을 가져오는

- Boolean : True / False
- true값은 출력
- False 값은 출력하지 않음

In [3]:
import numpy as np
# 임포트해주기

In [2]:
name = np.array(['희연','장훈','주란','종현'])
# 어레이를  리스트[] 안에 담아주기

In [4]:
name

array(['희연', '장훈', '주란', '종현'], dtype='<U2')

In [12]:
# boolean 자료형
bol = np.array([True,False,True,False])
bol

array([ True, False,  True, False])

In [13]:
# 불리언 인덱싱 
# bol이라는 변수에는 True가 두개있는데 True자리에 있는 값만 반환한다. 
name[bol]

array(['희연', '주란'], dtype='<U2')

In [21]:
# 데이터생성
name_score = np.array([['민지',80],['수호',90],['정민',100],['용재',70]])

In [23]:
name_score[ : ,0 ] == '정민'    #불리언

array([False, False,  True, False])

In [25]:
name_socore[ name_score[ : ,0 ] == '정민' ]  #불리언을 활용한 인덱싱

array([['정민', '100']], dtype='<U11')

# 다양한 함수들

In [31]:
# 1~10까지 담긴 1차원 배열 생성
arr = np.arange(1,11)

In [32]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
# 위에서 생성한 배열을 (2,5) 크기로 바꿔주기  ->요소의 갯수가 맞아야 바꿔줄 수 있음.
arr = arr.reshape(2,5)

In [38]:
# np.sum
# 총합, 요소 전체 더하기
print(np.sum(arr))
print(np.sum(arr, axis = 0))
print(np.sum(arr, axis = 1))

55
[ 7  9 11 13 15]
[15 40]


In [41]:
# np.mean() ->평균치  1부터 10까지 다더하고 10으로 나눈값
print(np.mean(arr))
print(np.mean(arr,axis=0))
print(np.mean(arr,axis=1))

5.5
[3.5 4.5 5.5 6.5 7.5]
[3. 8.]


In [43]:
# 절댓값 - 모두 양수로 표시하는거
# np.abs() -absolute

arr = np.array([1,-2,3,-4,5])
arr

array([ 1, -2,  3, -4,  5])

In [44]:
np.abs(arr)

array([1, 2, 3, 4, 5])

# 영화 평점 데이터 분석 실습

먼저데이터가있으면 그 데이터 형태를 파악하기 (데이터타입, 구조,구분자)

In [3]:
import numpy as np

In [7]:

# 데이터 불러오기  np.loadtxt('파일명.확장자' ,  delimiter='구분기호', dtype = '데이터형식')  ->txt파일ㅇ불러오기
data = np.loadtxt( 'ratings.txt', delimiter ='::', dtype = 'int')
print(data)

# user_id, 영화_id, 평점, timestamp

[[        1      1193         5 978300760]
 [        1       661         3 978302109]
 [        1       914         3 978301968]
 ...
 [     6040       562         5 956704746]
 [     6040      1096         4 956715648]
 [     6040      1097         4 956715569]]


In [12]:
#데이터 구조 파악하기
print(data.shape) #평점 개수
print(data.size) # 데이터 총 요소 개수 
print(data.ndim) 

(1000209, 4)
4000836
2


#### 1번 user의 전체 정보 출력 ->가져온다
- boolean 인덱싱 (조건에따라 가져오기)-데이터들이 차례로 정렬되어있다는 보증이없으닌까!

In [ ]:
# 1. 전체 데이터에서 id 정보만 가져오기

In [28]:
 data[ : , 0]

array([   1,    1,    1, ..., 6040, 6040, 6040])

In [ ]:
# 2. id가 1인지 판별

In [29]:

user_id = data[ : , 0] ==1   #true/false로 데이터를 나타내논

user_id

array([ True,  True,  True, ..., False, False, False])

In [ ]:
# 3.id가 1인 데이터만 가져오기

In [30]:
data[ user_id ]  #불리언 인덱싱



array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       [        1,      3408,         4, 978300275],
       [        1,      2355,         5, 978824291],
       [        1,      1197,         3, 978302268],
       [        1,      1287,         5, 978302039],
       [        1,      2804,         5, 978300719],
       [        1,       594,         4, 978302268],
       [        1,       919,         4, 978301368],
       [        1,       595,         5, 978824268],
       [        1,       938,         4, 978301752],
       [        1,      2398,         4, 978302281],
       [        1,      2918,         4, 978302124],
       [        1,      1035,         5, 978301753],
       [        1,      2791,         4, 978302188],
       [        1,      2687,         3, 978824268],
       [        1,      2018,         4, 978301777],
       [        1,      3105,         5, 97830

#### 전체 사용자의 평점 평균 구하기

In [34]:
# 1. 전체 데이터에서 평점 데이터만 가져오기
data[ : ,2]

# 2. 평균구하기
#np.mean(data[ : ,2])
data[ : ,2].mean()

3.581564453029317

#### 1번 사용자의 평점 평균 구하기

In [39]:
#1.1번 사용자 전체정보 - 평점데이터만가져오기
user_first = data[ user_id ] 

# 3.평균구하기
np.mean(user_first[ : ,2])
#user_first[ : ,2].mean()

4.188679245283019

##### 각 사용자의 평점 평균구하기

In [41]:
# 1번 사용자 평균

np.mean(data[data[ : ,0]==1][ : ,2])

#2번 사용자 평균
np.mean(data[data[ : ,0]==2][ : ,2])

# -> 반복문으로 사용자 id만 바꿔주면 된다. 
np.mean(data[data[ : ,0]==1][ : ,2])

3.7131782945736433

In [44]:
# 각 사용자의 id정보 필요
# 중복을 제거한 id정보 필요
user_idd = np.unique(data[ : ,0])
# ->중복을제거한 유일한 값만 출력

In [50]:
# 각 사용자의 평점 평균!
# for 반복문 

list1 =[]  #-> 사용자의 평균값을 담아줄 빈 리스트 생성

for user in user_idd:
    user_mean = np.mean(data[ data[ : , 0 ] == user ][ : , 2 ])
    list1.append( [ user, user_mean]) # [사용자 id, 평점평균]

In [51]:
list1

[[1, 4.188679245283019],
 [2, 3.7131782945736433],
 [3, 3.9019607843137254],
 [4, 4.190476190476191],
 [5, 3.1464646464646466],
 [6, 3.9014084507042255],
 [7, 4.32258064516129],
 [8, 3.884892086330935],
 [9, 3.7358490566037736],
 [10, 4.114713216957606],
 [11, 3.2773722627737225],
 [12, 3.8260869565217392],
 [13, 3.388888888888889],
 [14, 3.32],
 [15, 3.3233830845771144],
 [16, 3.0285714285714285],
 [17, 4.075829383886256],
 [18, 3.6491803278688524],
 [19, 3.5725490196078433],
 [20, 4.083333333333333],
 [21, 2.909090909090909],
 [22, 3.0673400673400675],
 [23, 3.3157894736842106],
 [24, 3.948529411764706],
 [25, 3.7411764705882353],
 [26, 2.96],
 [27, 4.171428571428572],
 [28, 3.7570093457943927],
 [29, 3.5833333333333335],
 [30, 3.488372093023256],
 [31, 3.73109243697479],
 [32, 3.625],
 [33, 3.498721227621483],
 [34, 3.8658536585365852],
 [35, 3.54040404040404],
 [36, 4.199430199430199],
 [37, 3.69811320754717],
 [38, 3.58],
 [39, 3.564516129032258],
 [40, 3.4479166666666665],
 [41, 

### 각 사용자 별 평균 평점이 4점 이상인 사용자 구하기

In [60]:
#리스트를 어레이로 만들어주기
# 어레이로 만들때 데이터타입 지정가능 dtype
ratings_mean = np.array(list1, dtype = 'int')
ratings_mean

array([[   1,    4],
       [   2,    3],
       [   3,    3],
       ...,
       [6038,    3],
       [6039,    3],
       [6040,    3]])

In [63]:
# 4점 이상이라는 조건 .-> boolean 인덱싱
# 평점데이터만 가져오기
ratings_mean[  : ,1] 


array([4, 3, 3, ..., 3, 3, 3])

In [65]:
# 4점 이상 판별
ratings_mean[  : ,1] >=4

array([ True, False, False, ..., False, False, False])

In [69]:
# 4점 이상  id 정보만 데이터 가져오기
ratings_mean[ : ,0][ratings_mean[  : ,1] >=4]
#ratings_mean[ratings_mean[  : ,1] >=4][ : ,0]

array([   1,    4,    7, ..., 6027, 6032, 6034])